#!/usr/bin/env node
/**
 * Render every chart recipe in a real browser, then write the skill's reference
 * page from the ones that drew.
 *
 *   node tools/verify-recipes.mjs [--emit]
 *
 * A recipe that does not render is worse than no recipe: the agent copies it,
 * the user gets an empty panel, and the failure looks like the agent's fault.
 * So the documentation is a build artifact of a passing test, not prose.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { RECIPES, allRecipesDashboard } from './recipes.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SERVER = process.env.SERVER_URL ?? 'http://localhost:8788';
const HARNESS = process.env.HARNESS_URL ?? 'http://localhost:8479/tools/harness.html';
const EMIT = process.argv.includes('--emit');
const SHOT = process.env.SCREENSHOT ?? null;

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM ?? '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1280, height: 2000 } });

const problems = [];
page.on('pageerror', error => problems.push(`page: ${error.message}`));
page.on('console', message => {
  const text = message.text();
  if (message.type() === 'error' && !text.includes('favicon')) problems.push(text);
  // Vega reports a broken encoding as a warning and then draws nothing, so a
  // warning here is a failure, not noise.
  if (message.type() === 'warning' && /WARN|Infinite extent|Unrecognized/.test(text)) problems.push(text);
});

await page.goto(`${HARNESS}?app=${SERVER}/app.html&server=${SERVER}`, { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);

// Hand the view a dashboard made of every recipe, exactly as the agent would.
await page.evaluate(async components => {
  await window.deliver('render_dashboard', { components, title: 'Every recipe' });
}, allRecipesDashboard());

await page.waitForTimeout(9000);

const view = page.frames().find(frame => frame !== page.mainFrame());
const drawn = await view.evaluate(() =>
  [...document.querySelectorAll('.section')].map(section => ({
    title: section.querySelector('.section__title')?.textContent ?? '',
    canvases: section.querySelectorAll('canvas').length,
    error: section.querySelector('.chart__error')?.textContent ?? null,
    empty: Boolean(section.querySelector('.chart__empty')),
  })),
);

let failed = 0;
for (const recipe of RECIPES) {
  const rendered = drawn.find(item => item.title === recipe.title);
  const ok = rendered && rendered.canvases > 0 && !rendered.error && !rendered.empty;
  if (!ok) failed++;
  process.stdout.write(
    `${ok ? 'ok  ' : 'FAIL'} ${recipe.id}${rendered?.error ? ` — ${rendered.error}` : ''}${rendered?.empty ? ' — drew nothing' : ''}\n`,
  );
}

if (problems.length) {
  process.stdout.write(`\n${problems.length} console problem(s):\n`);
  for (const problem of [...new Set(problems)].slice(0, 8)) process.stdout.write(`  ${problem}\n`);
}

if (SHOT) await page.screenshot({ path: SHOT, fullPage: true });
await browser.close();

if (failed || problems.length) {
  process.stdout.write(`\n${failed} recipe(s) failed\n`);
  process.exitCode = 1;
} else {
  process.stdout.write('\nevery recipe rendered\n');
  if (EMIT) emit();
}

/** Write the reference page the skill links to. */
function emit() {
  const out = path.join(ROOT, 'skills', 'a2ui-dashboards', 'references', 'recipes.md');
  const lines = [
    '# Chart recipes',
    '',
    '_Generated by `tools/verify-recipes.mjs`. Every recipe here was rendered in a',
    'browser against the real dataset before this file was written._',
    '',
    'Each one is the `spec` of a `VegaChart`. The component around it is always the',
    'same shape:',
    '',
    '```json',
    JSON.stringify(
      {
        id: 'chart_something',
        component: 'VegaChart',
        data: { path: '/datasets/ticket_sales/rows' },
        filters: [{ field: 'status', op: 'eq', value: 'paid' }],
        spec: { '…': 'one of the specs below' },
      },
      null,
      2,
    ),
    '```',
    '',
    'Columns in this dataset: `ordered_at` and `event_date` (temporal), `show`,',
    '`theatre`, `section`, `channel`, `promo_code`, `customer_segment`, `status`,',
    '`event_time` (nominal), `quantity`, `unit_price`, `gross` (quantitative).',
    '',
  ];

  for (const recipe of RECIPES) {
    lines.push(`## ${recipe.title}`, '', `**When:** ${recipe.when}`, '');
    if (recipe.note) lines.push(`> ${recipe.note}`, '');
    if (recipe.height) lines.push(`Set \`height: ${recipe.height}\` on the component.`, '');
    lines.push('```json', JSON.stringify(recipe.spec, null, 2), '```', '');
  }

  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, lines.join('\n'));
  process.stdout.write(`${path.relative(ROOT, out)} · ${RECIPES.length} recipes\n`);
}
